- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Configure Nginx reverse proxy
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

