- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Reset UFW to default
  ufw:
    state: reset

- name: Set UFW default policies
  ufw:
    direction: incoming
    policy: deny

- name: Allow outgoing traffic
  ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH (port 22) from anywhere
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow SSH (port 22) from anywhere
  ufw:
    rule: allow
    port: 1337
    proto: tcp

- name: Allow HTTP (port 80)
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS (port 443)
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Allow PostgreSQL (port 5432)
  ufw:
    rule: allow
    port: 5432
    proto: tcp

- name: Allow Frontend port (8080) from specific IPs
  ufw:
    rule: allow
    port: 8080
    proto: tcp
    from_ip: "{{ item }}"
  loop: "{{ allowed_ips }}"

- name: Allow Backend port (8081) from specific IPs
  ufw:
    rule: allow
    port: 8081
    proto: tcp
    from_ip: "{{ item }}"
  loop: "{{ allowed_ips }}"

- name: Enable UFW
  ufw:
    state: enabled


- name: Harden SSH Configuration
  become: yes
  block:
    - name: Backup original sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: yes

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin\s+.*'
        line: 'PermitRootLogin no'
        state: present

    - name: Change SSH port to 1337
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port\s+.*'
        line: 'Port 1337'
        state: present

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication\s+.*'
        line: 'PasswordAuthentication no'
        state: present

    - name: Ensure firewall allows new SSH port (1337)
      ufw:
        rule: allow
        port: 1337
        proto: tcp

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted









