- name: Deploy the Java application.
  become: yes
  block:

    - name: Ensure AWS CLI is installed
      apt:
        name: awscli
        state: present
      become: yes

    - name: Create application directory
      file:
        path: /home/ubuntu/ansible/docker-app
        state: directory
        mode: '0755'

    - name: Upload .env file
      copy:
        src: /home/ubuntu/ansible/templates/.env
        dest: /home/ubuntu/ansible/docker-app/.env
        mode: '0600'

    - name: Authenticate with AWS ECR
      shell: |
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 992122884453.dkr.ecr.eu-central-1.amazonaws.com
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      args:
        executable: /bin/bash

    - name: Pull Docker image from ECR
      docker_image:
        name: "{{ item }}"
        tag: "latest"
        source: pull
      loop: "{{ ecr_uris }}"

    - name: Stop and remove any existing container
      docker_container:
        name: "{{ item }}"
        state: absent
        force_kill: true
      loop: "{{ docker_containers }}"

    - name: Run the backend container
      docker_container:
        name: validator-backend-image
        image: "{{ ecr_uris[0] }}:latest"
        env_file: /home/ubuntu/ansible/docker-app/.env
        ports:
          - "8080:8080"
        restart_policy: always
